services:
  locust-master:
    container_name: locust-master
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: >
      -f /mnt/locust/locustfile-test.py
      --master
      -H http://host.docker.internal:8080

  locust-worker:
    container_name: locust-worker
    image: locustio/locust
    depends_on:
      - locust-master
    volumes:
      - ./:/mnt/locust
    command: >
      -f /mnt/locust/locustfile-test.py
      --worker
      --master-host locust-master